version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s apache2-foreground

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "senha_da_nasa"
      MYSQL_DATABASE: atividadeavaliativaidss5
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./sql/products.sql:/docker-entrypoint-initdb.d/products.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "senha_da_nasa"
    ports:
      - "8081:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge